version: "3.9"

networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16


services:
  client:
    image: docker-client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    networks:
      - default
      - net1
    # network_mode: "service:docker-vm-deamon"
    environment:
      DOCKER_HOST: tcp://10.40.1.18:2375
    # cap_add:
    #   - ALL

  # docker-vm-deamon:
  #   image: docker-host
  #   build:
  #     context: ./
  #     dockerfile: ./deamon/Dockerfile
  #   privileged: true
  #   network_mode: "host"
  #   # expose:
  #   #   - 2375
  #   #   - 2377 
  #   #   - 7946
  #   #   - 4789
  #   # networks:
  #   #   default:
  #   #   net1:
  #   #     ipv4_address: 172.21.1.18
  #   volumes:
  #     - "/tmp:/tmp"
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #     - "/lib/modules:/lib/modules"
  #   devices:
  #     - "/dev/vboxdrv:/dev/vboxdrv"
  #   cap_add:
  #     - ALL